package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Addinvoice generated by hbm2java
 */
public class Addinvoice  implements java.io.Serializable {


     private Integer idAddinvoice;
     private Addreg addreg;
     private Date date;
     private Double amount;

    public Addinvoice() {
    }

	
    public Addinvoice(Addreg addreg) {
        this.addreg = addreg;
    }
    public Addinvoice(Addreg addreg, Date date, Double amount) {
       this.addreg = addreg;
       this.date = date;
       this.amount = amount;
    }
   
    public Integer getIdAddinvoice() {
        return this.idAddinvoice;
    }
    
    public void setIdAddinvoice(Integer idAddinvoice) {
        this.idAddinvoice = idAddinvoice;
    }
    public Addreg getAddreg() {
        return this.addreg;
    }
    
    public void setAddreg(Addreg addreg) {
        this.addreg = addreg;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


