package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer idAdmin;
     private String fistName;
     private String lastName;
     private String nic;
     private String email;
     private String mobile;
     private Set statuses = new HashSet(0);
     private Set adminlogins = new HashSet(0);

    public Admin() {
    }

    public Admin(String fistName, String lastName, String nic, String email, String mobile, Set statuses, Set adminlogins) {
       this.fistName = fistName;
       this.lastName = lastName;
       this.nic = nic;
       this.email = email;
       this.mobile = mobile;
       this.statuses = statuses;
       this.adminlogins = adminlogins;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getFistName() {
        return this.fistName;
    }
    
    public void setFistName(String fistName) {
        this.fistName = fistName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }
    public Set getAdminlogins() {
        return this.adminlogins;
    }
    
    public void setAdminlogins(Set adminlogins) {
        this.adminlogins = adminlogins;
    }




}


