package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catagory1 generated by hbm2java
 */
public class Catagory1  implements java.io.Serializable {


     private Integer idCatagory1;
     private String name;
     private Set brands = new HashSet(0);
     private Set products = new HashSet(0);
     private Set models = new HashSet(0);
     private Set catagory2s = new HashSet(0);

    public Catagory1() {
    }

    public Catagory1(String name, Set brands, Set products, Set models, Set catagory2s) {
       this.name = name;
       this.brands = brands;
       this.products = products;
       this.models = models;
       this.catagory2s = catagory2s;
    }
   
    public Integer getIdCatagory1() {
        return this.idCatagory1;
    }
    
    public void setIdCatagory1(Integer idCatagory1) {
        this.idCatagory1 = idCatagory1;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBrands() {
        return this.brands;
    }
    
    public void setBrands(Set brands) {
        this.brands = brands;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }
    public Set getModels() {
        return this.models;
    }
    
    public void setModels(Set models) {
        this.models = models;
    }
    public Set getCatagory2s() {
        return this.catagory2s;
    }
    
    public void setCatagory2s(Set catagory2s) {
        this.catagory2s = catagory2s;
    }




}


