package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private Integer idColor;
     private String name;
     private Set productHasColors = new HashSet(0);
     private Set invoiceinformations = new HashSet(0);

    public Color() {
    }

    public Color(String name, Set productHasColors, Set invoiceinformations) {
       this.name = name;
       this.productHasColors = productHasColors;
       this.invoiceinformations = invoiceinformations;
    }
   
    public Integer getIdColor() {
        return this.idColor;
    }
    
    public void setIdColor(Integer idColor) {
        this.idColor = idColor;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductHasColors() {
        return this.productHasColors;
    }
    
    public void setProductHasColors(Set productHasColors) {
        this.productHasColors = productHasColors;
    }
    public Set getInvoiceinformations() {
        return this.invoiceinformations;
    }
    
    public void setInvoiceinformations(Set invoiceinformations) {
        this.invoiceinformations = invoiceinformations;
    }




}


