package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Delavary generated by hbm2java
 */
public class Delavary  implements java.io.Serializable {


     private Integer idDelavary;
     private Double startAmount;
     private String name;
     private Double payForKm;
     private Double maxAmount;
     private Set invoices = new HashSet(0);

    public Delavary() {
    }

    public Delavary(Double startAmount, String name, Double payForKm, Double maxAmount, Set invoices) {
       this.startAmount = startAmount;
       this.name = name;
       this.payForKm = payForKm;
       this.maxAmount = maxAmount;
       this.invoices = invoices;
    }
   
    public Integer getIdDelavary() {
        return this.idDelavary;
    }
    
    public void setIdDelavary(Integer idDelavary) {
        this.idDelavary = idDelavary;
    }
    public Double getStartAmount() {
        return this.startAmount;
    }
    
    public void setStartAmount(Double startAmount) {
        this.startAmount = startAmount;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPayForKm() {
        return this.payForKm;
    }
    
    public void setPayForKm(Double payForKm) {
        this.payForKm = payForKm;
    }
    public Double getMaxAmount() {
        return this.maxAmount;
    }
    
    public void setMaxAmount(Double maxAmount) {
        this.maxAmount = maxAmount;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


