package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distype generated by hbm2java
 */
public class Distype  implements java.io.Serializable {


     private Integer idDisType;
     private String type;
     private Set discounts = new HashSet(0);

    public Distype() {
    }

    public Distype(String type, Set discounts) {
       this.type = type;
       this.discounts = discounts;
    }
   
    public Integer getIdDisType() {
        return this.idDisType;
    }
    
    public void setIdDisType(Integer idDisType) {
        this.idDisType = idDisType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Set discounts) {
        this.discounts = discounts;
    }




}


