package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * District generated by hbm2java
 */
public class District  implements java.io.Serializable {


     private Integer idDistrict;
     private String name;

    public District() {
    }

    public District(String name) {
       this.name = name;
    }
   
    public Integer getIdDistrict() {
        return this.idDistrict;
    }
    
    public void setIdDistrict(Integer idDistrict) {
        this.idDistrict = idDistrict;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


