package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Donateamount generated by hbm2java
 */
public class Donateamount  implements java.io.Serializable {


     private Integer idDonateAmount;
     private Donateresion donateresion;
     private User user;
     private Double amount;
     private Set invoices = new HashSet(0);

    public Donateamount() {
    }

	
    public Donateamount(Donateresion donateresion, User user) {
        this.donateresion = donateresion;
        this.user = user;
    }
    public Donateamount(Donateresion donateresion, User user, Double amount, Set invoices) {
       this.donateresion = donateresion;
       this.user = user;
       this.amount = amount;
       this.invoices = invoices;
    }
   
    public Integer getIdDonateAmount() {
        return this.idDonateAmount;
    }
    
    public void setIdDonateAmount(Integer idDonateAmount) {
        this.idDonateAmount = idDonateAmount;
    }
    public Donateresion getDonateresion() {
        return this.donateresion;
    }
    
    public void setDonateresion(Donateresion donateresion) {
        this.donateresion = donateresion;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


