package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Donateresion generated by hbm2java
 */
public class Donateresion  implements java.io.Serializable {


     private Integer idDonateResion;
     private String name;
     private String states;
     private Set donateamounts = new HashSet(0);

    public Donateresion() {
    }

    public Donateresion(String name, String states, Set donateamounts) {
       this.name = name;
       this.states = states;
       this.donateamounts = donateamounts;
    }
   
    public Integer getIdDonateResion() {
        return this.idDonateResion;
    }
    
    public void setIdDonateResion(Integer idDonateResion) {
        this.idDonateResion = idDonateResion;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStates() {
        return this.states;
    }
    
    public void setStates(String states) {
        this.states = states;
    }
    public Set getDonateamounts() {
        return this.donateamounts;
    }
    
    public void setDonateamounts(Set donateamounts) {
        this.donateamounts = donateamounts;
    }




}


