package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * Faq generated by hbm2java
 */
public class Faq  implements java.io.Serializable {


     private Integer idFaq;
     private String quatation;
     private String answer;

    public Faq() {
    }

    public Faq(String quatation, String answer) {
       this.quatation = quatation;
       this.answer = answer;
    }
   
    public Integer getIdFaq() {
        return this.idFaq;
    }
    
    public void setIdFaq(Integer idFaq) {
        this.idFaq = idFaq;
    }
    public String getQuatation() {
        return this.quatation;
    }
    
    public void setQuatation(String quatation) {
        this.quatation = quatation;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


