package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * Fistpage generated by hbm2java
 */
public class Fistpage  implements java.io.Serializable {


     private Integer idFistPage;
     private Product product;

    public Fistpage() {
    }

    public Fistpage(Product product) {
       this.product = product;
    }
   
    public Integer getIdFistPage() {
        return this.idFistPage;
    }
    
    public void setIdFistPage(Integer idFistPage) {
        this.idFistPage = idFistPage;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


