package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender  implements java.io.Serializable {


     private Integer idGender;
     private String name;
     private Set users = new HashSet(0);

    public Gender() {
    }

    public Gender(String name, Set users) {
       this.name = name;
       this.users = users;
    }
   
    public Integer getIdGender() {
        return this.idGender;
    }
    
    public void setIdGender(Integer idGender) {
        this.idGender = idGender;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


