package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer imageid;
     private Addreg addreg;
     private String im1;
     private String im2;
     private String im3;
     private String im4;

    public Image() {
    }

	
    public Image(Addreg addreg) {
        this.addreg = addreg;
    }
    public Image(Addreg addreg, String im1, String im2, String im3, String im4) {
       this.addreg = addreg;
       this.im1 = im1;
       this.im2 = im2;
       this.im3 = im3;
       this.im4 = im4;
    }
   
    public Integer getImageid() {
        return this.imageid;
    }
    
    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }
    public Addreg getAddreg() {
        return this.addreg;
    }
    
    public void setAddreg(Addreg addreg) {
        this.addreg = addreg;
    }
    public String getIm1() {
        return this.im1;
    }
    
    public void setIm1(String im1) {
        this.im1 = im1;
    }
    public String getIm2() {
        return this.im2;
    }
    
    public void setIm2(String im2) {
        this.im2 = im2;
    }
    public String getIm3() {
        return this.im3;
    }
    
    public void setIm3(String im3) {
        this.im3 = im3;
    }
    public String getIm4() {
        return this.im4;
    }
    
    public void setIm4(String im4) {
        this.im4 = im4;
    }




}


