package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private Delavary delavary;
     private Donateamount donateamount;
     private User user;
     private String date;
     private String time;
     private Double amount;
     private double shAmount;
     private Set invoiceinformations = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(Delavary delavary, Donateamount donateamount, User user, double shAmount) {
        this.delavary = delavary;
        this.donateamount = donateamount;
        this.user = user;
        this.shAmount = shAmount;
    }
    public Invoice(Delavary delavary, Donateamount donateamount, User user, String date, String time, Double amount, double shAmount, Set invoiceinformations) {
       this.delavary = delavary;
       this.donateamount = donateamount;
       this.user = user;
       this.date = date;
       this.time = time;
       this.amount = amount;
       this.shAmount = shAmount;
       this.invoiceinformations = invoiceinformations;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public Delavary getDelavary() {
        return this.delavary;
    }
    
    public void setDelavary(Delavary delavary) {
        this.delavary = delavary;
    }
    public Donateamount getDonateamount() {
        return this.donateamount;
    }
    
    public void setDonateamount(Donateamount donateamount) {
        this.donateamount = donateamount;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public double getShAmount() {
        return this.shAmount;
    }
    
    public void setShAmount(double shAmount) {
        this.shAmount = shAmount;
    }
    public Set getInvoiceinformations() {
        return this.invoiceinformations;
    }
    
    public void setInvoiceinformations(Set invoiceinformations) {
        this.invoiceinformations = invoiceinformations;
    }




}


