package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoiceinformation generated by hbm2java
 */
public class Invoiceinformation  implements java.io.Serializable {


     private Integer idinvoiceInformationcol;
     private Color color;
     private Invoice invoice;
     private Product product;
     private Set rattings = new HashSet(0);

    public Invoiceinformation() {
    }

	
    public Invoiceinformation(Color color, Invoice invoice, Product product) {
        this.color = color;
        this.invoice = invoice;
        this.product = product;
    }
    public Invoiceinformation(Color color, Invoice invoice, Product product, Set rattings) {
       this.color = color;
       this.invoice = invoice;
       this.product = product;
       this.rattings = rattings;
    }
   
    public Integer getIdinvoiceInformationcol() {
        return this.idinvoiceInformationcol;
    }
    
    public void setIdinvoiceInformationcol(Integer idinvoiceInformationcol) {
        this.idinvoiceInformationcol = idinvoiceInformationcol;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Set getRattings() {
        return this.rattings;
    }
    
    public void setRattings(Set rattings) {
        this.rattings = rattings;
    }




}


