package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private User user;
     private String password;
     private String email;
     private String validation;

    public Login() {
    }

	
    public Login(User user) {
        this.user = user;
    }
    public Login(User user, String password, String email, String validation) {
       this.user = user;
       this.password = password;
       this.email = email;
       this.validation = validation;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getValidation() {
        return this.validation;
    }
    
    public void setValidation(String validation) {
        this.validation = validation;
    }




}


