package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private Integer idModel;
     private Brand brand;
     private Catagory1 catagory1;
     private Catagory2 catagory2;
     private String name;
     private Set products = new HashSet(0);

    public Model() {
    }

	
    public Model(Brand brand, Catagory1 catagory1, Catagory2 catagory2) {
        this.brand = brand;
        this.catagory1 = catagory1;
        this.catagory2 = catagory2;
    }
    public Model(Brand brand, Catagory1 catagory1, Catagory2 catagory2, String name, Set products) {
       this.brand = brand;
       this.catagory1 = catagory1;
       this.catagory2 = catagory2;
       this.name = name;
       this.products = products;
    }
   
    public Integer getIdModel() {
        return this.idModel;
    }
    
    public void setIdModel(Integer idModel) {
        this.idModel = idModel;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Catagory1 getCatagory1() {
        return this.catagory1;
    }
    
    public void setCatagory1(Catagory1 catagory1) {
        this.catagory1 = catagory1;
    }
    public Catagory2 getCatagory2() {
        return this.catagory2;
    }
    
    public void setCatagory2(Catagory2 catagory2) {
        this.catagory2 = catagory2;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


