package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Msg generated by hbm2java
 */
public class Msg  implements java.io.Serializable {


     private Integer idMsg;
     private User user;
     private String msg;
     private Date date;

    public Msg() {
    }

	
    public Msg(User user) {
        this.user = user;
    }
    public Msg(User user, String msg, Date date) {
       this.user = user;
       this.msg = msg;
       this.date = date;
    }
   
    public Integer getIdMsg() {
        return this.idMsg;
    }
    
    public void setIdMsg(Integer idMsg) {
        this.idMsg = idMsg;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


