package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productstates generated by hbm2java
 */
public class Productstates  implements java.io.Serializable {


     private Integer idProductStates;
     private String name;
     private Set products = new HashSet(0);

    public Productstates() {
    }

    public Productstates(String name, Set products) {
       this.name = name;
       this.products = products;
    }
   
    public Integer getIdProductStates() {
        return this.idProductStates;
    }
    
    public void setIdProductStates(Integer idProductStates) {
        this.idProductStates = idProductStates;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


