package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idProduct;
     private Brand brand;
     private Catagory1 catagory1;
     private Catagory2 catagory2;
     private Model model;
     private Productstates productstates;
     private Size size;
     private String name;
     private String discription;
     private Integer qty;
     private Double amount;
     private Set fistpages = new HashSet(0);
     private Set rattings = new HashSet(0);
     private Set discounts = new HashSet(0);
     private Set productimages = new HashSet(0);
     private Set wishLists = new HashSet(0);
     private Set productHasColors = new HashSet(0);
     private Set invoiceinformations = new HashSet(0);

    public Product() {
    }

	
    public Product(Brand brand, Catagory1 catagory1, Catagory2 catagory2, Model model, Productstates productstates, Size size) {
        this.brand = brand;
        this.catagory1 = catagory1;
        this.catagory2 = catagory2;
        this.model = model;
        this.productstates = productstates;
        this.size = size;
    }
    public Product(Brand brand, Catagory1 catagory1, Catagory2 catagory2, Model model, Productstates productstates, Size size, String name, String discription, Integer qty, Double amount, Set fistpages, Set rattings, Set discounts, Set productimages, Set wishLists, Set productHasColors, Set invoiceinformations) {
       this.brand = brand;
       this.catagory1 = catagory1;
       this.catagory2 = catagory2;
       this.model = model;
       this.productstates = productstates;
       this.size = size;
       this.name = name;
       this.discription = discription;
       this.qty = qty;
       this.amount = amount;
       this.fistpages = fistpages;
       this.rattings = rattings;
       this.discounts = discounts;
       this.productimages = productimages;
       this.wishLists = wishLists;
       this.productHasColors = productHasColors;
       this.invoiceinformations = invoiceinformations;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Catagory1 getCatagory1() {
        return this.catagory1;
    }
    
    public void setCatagory1(Catagory1 catagory1) {
        this.catagory1 = catagory1;
    }
    public Catagory2 getCatagory2() {
        return this.catagory2;
    }
    
    public void setCatagory2(Catagory2 catagory2) {
        this.catagory2 = catagory2;
    }
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    public Productstates getProductstates() {
        return this.productstates;
    }
    
    public void setProductstates(Productstates productstates) {
        this.productstates = productstates;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Set getFistpages() {
        return this.fistpages;
    }
    
    public void setFistpages(Set fistpages) {
        this.fistpages = fistpages;
    }
    public Set getRattings() {
        return this.rattings;
    }
    
    public void setRattings(Set rattings) {
        this.rattings = rattings;
    }
    public Set getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Set discounts) {
        this.discounts = discounts;
    }
    public Set getProductimages() {
        return this.productimages;
    }
    
    public void setProductimages(Set productimages) {
        this.productimages = productimages;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }
    public Set getProductHasColors() {
        return this.productHasColors;
    }
    
    public void setProductHasColors(Set productHasColors) {
        this.productHasColors = productHasColors;
    }
    public Set getInvoiceinformations() {
        return this.invoiceinformations;
    }
    
    public void setInvoiceinformations(Set invoiceinformations) {
        this.invoiceinformations = invoiceinformations;
    }




}


