package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * Quackanswer generated by hbm2java
 */
public class Quackanswer  implements java.io.Serializable {


     private Integer idquackanswer;
     private String name;
     private String data;

    public Quackanswer() {
    }

    public Quackanswer(String name, String data) {
       this.name = name;
       this.data = data;
    }
   
    public Integer getIdquackanswer() {
        return this.idquackanswer;
    }
    
    public void setIdquackanswer(Integer idquackanswer) {
        this.idquackanswer = idquackanswer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


