package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserStatus generated by hbm2java
 */
public class UserStatus  implements java.io.Serializable {


     private Integer idUserStatus;
     private String name;
     private Set users = new HashSet(0);

    public UserStatus() {
    }

    public UserStatus(String name, Set users) {
       this.name = name;
       this.users = users;
    }
   
    public Integer getIdUserStatus() {
        return this.idUserStatus;
    }
    
    public void setIdUserStatus(Integer idUserStatus) {
        this.idUserStatus = idUserStatus;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


