package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Gender gender;
     private UserStatus userStatus;
     private String fistName;
     private String lastName;
     private String nic;
     private String address1;
     private String address2;
     private String city;
     private String district;
     private String mobileNo;
     private String email;
     private String userType;
     private Set userroles = new HashSet(0);
     private Set addregs = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set wishLists = new HashSet(0);
     private Set loginreports = new HashSet(0);
     private Set msgs = new HashSet(0);
     private Set donateamounts = new HashSet(0);
     private Set userfeedbacks = new HashSet(0);

    public User() {
    }

	
    public User(Gender gender, UserStatus userStatus) {
        this.gender = gender;
        this.userStatus = userStatus;
    }
    public User(Gender gender, UserStatus userStatus, String fistName, String lastName, String nic, String address1, String address2, String city, String district, String mobileNo, String email, String userType, Set userroles, Set addregs, Set invoices, Set logins, Set wishLists, Set loginreports, Set msgs, Set donateamounts, Set userfeedbacks) {
       this.gender = gender;
       this.userStatus = userStatus;
       this.fistName = fistName;
       this.lastName = lastName;
       this.nic = nic;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.district = district;
       this.mobileNo = mobileNo;
       this.email = email;
       this.userType = userType;
       this.userroles = userroles;
       this.addregs = addregs;
       this.invoices = invoices;
       this.logins = logins;
       this.wishLists = wishLists;
       this.loginreports = loginreports;
       this.msgs = msgs;
       this.donateamounts = donateamounts;
       this.userfeedbacks = userfeedbacks;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public UserStatus getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(UserStatus userStatus) {
        this.userStatus = userStatus;
    }
    public String getFistName() {
        return this.fistName;
    }
    
    public void setFistName(String fistName) {
        this.fistName = fistName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Set userroles) {
        this.userroles = userroles;
    }
    public Set getAddregs() {
        return this.addregs;
    }
    
    public void setAddregs(Set addregs) {
        this.addregs = addregs;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }
    public Set getLoginreports() {
        return this.loginreports;
    }
    
    public void setLoginreports(Set loginreports) {
        this.loginreports = loginreports;
    }
    public Set getMsgs() {
        return this.msgs;
    }
    
    public void setMsgs(Set msgs) {
        this.msgs = msgs;
    }
    public Set getDonateamounts() {
        return this.donateamounts;
    }
    
    public void setDonateamounts(Set donateamounts) {
        this.donateamounts = donateamounts;
    }
    public Set getUserfeedbacks() {
        return this.userfeedbacks;
    }
    
    public void setUserfeedbacks(Set userfeedbacks) {
        this.userfeedbacks = userfeedbacks;
    }




}


