package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1



/**
 * Userfeedback generated by hbm2java
 */
public class Userfeedback  implements java.io.Serializable {


     private Integer idUserFeedback;
     private User user;
     private String name;

    public Userfeedback() {
    }

	
    public Userfeedback(User user) {
        this.user = user;
    }
    public Userfeedback(User user, String name) {
       this.user = user;
       this.name = name;
    }
   
    public Integer getIdUserFeedback() {
        return this.idUserFeedback;
    }
    
    public void setIdUserFeedback(Integer idUserFeedback) {
        this.idUserFeedback = idUserFeedback;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


