package Databasefile;
// Generated Jan 7, 2016 12:21:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WishList generated by hbm2java
 */
public class WishList  implements java.io.Serializable {


     private Integer idWishList;
     private Product product;
     private ProductHasColor productHasColor;
     private User user;
     private Integer qty;
     private Date date;
     private Date expDate;

    public WishList() {
    }

	
    public WishList(Product product, ProductHasColor productHasColor, User user) {
        this.product = product;
        this.productHasColor = productHasColor;
        this.user = user;
    }
    public WishList(Product product, ProductHasColor productHasColor, User user, Integer qty, Date date, Date expDate) {
       this.product = product;
       this.productHasColor = productHasColor;
       this.user = user;
       this.qty = qty;
       this.date = date;
       this.expDate = expDate;
    }
   
    public Integer getIdWishList() {
        return this.idWishList;
    }
    
    public void setIdWishList(Integer idWishList) {
        this.idWishList = idWishList;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public ProductHasColor getProductHasColor() {
        return this.productHasColor;
    }
    
    public void setProductHasColor(ProductHasColor productHasColor) {
        this.productHasColor = productHasColor;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getExpDate() {
        return this.expDate;
    }
    
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }




}


